apiVersion: v1
kind: Secret
metadata:
  # this is the jenkins id.
  name: "another-test-file"
  labels:
    # so we know what type it is.
    "jenkins.io/credentials-type": "<<CREDENTIAL_TYPE>>"
  annotations:
    # description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "<<CREDENTIAL_DESC>>"
type: Opaque
stringData:
  filename: "<<SECRET FILE NAME>>"
data:
  # base64 encoded bytes
  data: "<<SECRET BYTES CONTEN>>"